Perform numerical analysis and data manipulate usig the numpy libraries


1.create a numpy array

In [3]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


2.Access and manipulate element i the array 

In [4]:
arr1[2]

3

In [5]:
arr1[2]=5
arr1

array([1, 2, 5])

3.Create a 2 dimensional array and check the shape of the array

In [7]:
arr2=np.array(([1,2,3],[4,5,6]))
print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
print ("the shape is 2 rows and 3 coloumns",arr2.shape)

the shape is 2 rows and 3 coloumns (2, 3)


4.Access elements from the 2D array using index position

In [9]:
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


5.Create a array of the string 

In [10]:
arr3=np.array(['india','china','USA','Canada'])
print(arr3)

['india' 'china' 'USA' 'Canada']


In [17]:
arr3[1]

'china'

6.Using the arrange()  and linspace() fuction to evenly space values in a specified interval

In [48]:
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [21]:
arr=np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


7.Create an array of random values between 0and 1 in a given shape

In [22]:
arr=np.random .rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)

[0.61727532 0.63322114 0.20236913 0.44769404 0.95855344 0.43184322
 0.64840729 0.89145605 0.89315443 0.86814128]


[[0.61868274 0.80214272 0.78388071 0.48796287]
 [0.90923224 0.96974026 0.91840574 0.27313109]
 [0.15897141 0.54446531 0.58575149 0.04524255]]


8.Create an array of constant values  in a given shape

In [23]:
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


9.Repeat each element of an array by a specified number of times using
 repeat() and title() functions

In [24]:
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [26]:
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


10.Create an identity matrixusing eye() and identity() function

In [27]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11.Create a 5X5 2D array for random numbers between 0 and 1

In [49]:
arr=np.random.rand(5,5)
print(arr)

[[0.67999591 0.83660808 0.42116244 0.26719244 0.57954893]
 [0.36227679 0.45593594 0.87193467 0.41340234 0.98226078]
 [0.03346589 0.64023147 0.29656208 0.36373934 0.67296215]
 [0.8172154  0.56237848 0.80186901 0.01621644 0.57006445]
 [0.52212463 0.20305661 0.57788944 0.22580134 0.02807507]]


12.Sum an array along the coloumn 

In [33]:
print (np.sum(arr,axis=0))

[1.89106111 2.10940548 2.13804088 1.86797137]


13.sum an array aong the row

In [34]:
print (np.sum(arr,axis=1))

[2.42844861 1.84708106 1.38099324 2.34995594]


14.calculate the mean,median,standard,deviation and variance

In [35]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.5004049280885896
0.5151576184512601
0.2345608286216031
0.05501878232365306


15.Sort an array along the row using the sort() function

In [40]:
arr=np.random.rand(5,5)
print(arr)

[[0.06630684 0.72191356 0.62984491 0.27790016 0.28645924]
 [0.00361971 0.84053766 0.28077273 0.80190874 0.08945891]
 [0.35890074 0.31894596 0.17396843 0.23118356 0.22089627]
 [0.0100298  0.69450504 0.32752892 0.57332259 0.98822266]
 [0.0844641  0.25894446 0.25326813 0.21607867 0.39198773]]


In [41]:
print(np.sort(arr,axis=1))

[[0.06630684 0.27790016 0.28645924 0.62984491 0.72191356]
 [0.00361971 0.08945891 0.28077273 0.80190874 0.84053766]
 [0.17396843 0.22089627 0.23118356 0.31894596 0.35890074]
 [0.0100298  0.32752892 0.57332259 0.69450504 0.98822266]
 [0.0844641  0.21607867 0.25326813 0.25894446 0.39198773]]


16.Append elements to an array using the append() function

In [42]:
ar=np.array([4,5,6,7])
arr1=np.append(arr,8)
arr1

array([6.63068418e-02, 7.21913561e-01, 6.29844908e-01, 2.77900164e-01,
       2.86459239e-01, 3.61971269e-03, 8.40537656e-01, 2.80772735e-01,
       8.01908743e-01, 8.94589131e-02, 3.58900745e-01, 3.18945963e-01,
       1.73968429e-01, 2.31183556e-01, 2.20896266e-01, 1.00298006e-02,
       6.94505039e-01, 3.27528920e-01, 5.73322592e-01, 9.88222655e-01,
       8.44640972e-02, 2.58944462e-01, 2.53268128e-01, 2.16078666e-01,
       3.91987729e-01, 8.00000000e+00])

In [43]:
arr2=np.append(arr,[9,10,11])
print(arr2)

[6.63068418e-02 7.21913561e-01 6.29844908e-01 2.77900164e-01
 2.86459239e-01 3.61971269e-03 8.40537656e-01 2.80772735e-01
 8.01908743e-01 8.94589131e-02 3.58900745e-01 3.18945963e-01
 1.73968429e-01 2.31183556e-01 2.20896266e-01 1.00298006e-02
 6.94505039e-01 3.27528920e-01 5.73322592e-01 9.88222655e-01
 8.44640972e-02 2.58944462e-01 2.53268128e-01 2.16078666e-01
 3.91987729e-01 9.00000000e+00 1.00000000e+01 1.10000000e+01]


17.Delete multiple elements in an array 

In [51]:
arr2=np.array([4,5,6,7,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


18.Concatenate element from 2 arrays

In [45]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [46]:
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
